### ISSUE TITLE
v1.3.5 crashes when trying to record screen

### ISSUE THREAD

**Issue by thekamilpro** [lihaoyun6/QuickRecorder#79]
MacOs 14.5

Steps to reproduce:

Install 1.3.5 (I Upgraded from 1.3.2)
Select screen area (Window option works)
The app crashes

**Comment by Mobiusium** [comment]
In addition, when trying to edit area size the app also crashes.
除此之外，当尝试编辑区域大小时，应用程序也会崩溃。

https://github.com/lihaoyun6/QuickRecorder/assets/36825968/94e4f60a-f8a3-4e3c-a9df-5c8f75b7d6d6

**Comment by lihaoyun6** [comment]
Since macOS 15 SDK enhances the equatable check for SwiftUI View.  And my shitty code triggers the `AttributeGraph` crash. 😢 I'm sorry about that, this issue has been fixed in the v1.3.7.  

由于 macOS 15 SDK 中加强了对 SwiftUI View 的相等性验证, 所以我的那堆烂代码不出意外的在使用新 SDK 编译后触发了 `AttributeGraph` 崩溃. 😢 十分不好意思, 不过这个问题已经在 v1.3.7 版本中得到了修复.
